version: '2'
services:
    baseapp-app:
        image: baseapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=baseapp-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    baseapp-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: baseapp-cassandra
    baseapp-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=baseapp-cassandra
    baseapp-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: baseapp-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
